services:
  server:
    container_name: ecom
    build: 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgresdb
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.docker
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: